leadshop/accounts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r"^signup/$", views.MerchantRegistration.as_view(), name='merchant_signup'),
    url(r"^activate/(?P<uid>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$",
        views.ActivateUser.as_view(), name='activate'),
    url(r"^login/success/", views.LoginSuccess.as_view(), name='login_success'),
]

leadshop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from . import views
from leadshop.accounts import views as account_views

urlpatterns = [
    url(r"^$", views.Home.as_view(), name="home"),
    url(r'^admin/', admin.site.urls),
    url(r'^merchant/accounts/', include("leadshop.accounts.urls", namespace="accounts")),
    url(r"^login/$", auth_views.login, {'template_name': 'accounts/login.html'}, name="login"),
    url(r"^logout/$", account_views.LoginOut.as_view(), name="logout"),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^merchant/dashboard', include("leadshop.merchant.urls", namespace="merchant")),
]

leadshop/accounts/models.py
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
    PermissionsMixin
)
from django.db import models
from django.utils import timezone


class UserManager(BaseUserManager):
    def create_user(self, email, username, password, is_merchant=False):
        if not email:
            raise ValueError("User must have an email address")
        if not username:
            raise ValueError("User must have a username")
        if not password:
            raise ValueError("Password cannot be empty")

        user = self.model(
            email=self.normalize_email(email),
            username=username,
            is_merchant=is_merchant
        )
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, username, password):
        user = self.create_user(
            email,
            username,
            password
        )
        user.is_active = True
        user.is_staff = True
        user.is_superuser = True
        user.save()
        return user


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=40, unique=True)
    date_joined = models.DateTimeField(default=timezone.now)
    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_merchant = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]

    def __str__(self):
        return "@{}".format(self.username)

    def get_short_name(self):
        return self.username

    def get_long_name(self):
        return "{} (@{})".format(self.email, self.username)

leadshop/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from . import emails


class UserCreateForm(UserCreationForm):
    """
    Form class to which persists a User into the database.
    """

    class Meta:
        fields = ('email', 'username', 'password1', 'password2')
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = "Username"
        self.fields['email'].label = "Email Address"

    def save(self, commit=True):
        """
        The user data is saved if it is valid and also a user is sent a
        verification email upon successful sign up.
        :param commit:
        :return:
        """
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.is_merchant = True
        if commit:
            user.save()
            emails.send_user_registration_activation_email(self.request, user, user.email)
        return user

accounts/views.py
from django.contrib.auth import get_user_model, logout
from django.http import HttpResponse
from django.shortcuts import redirect
from django.core.urlresolvers import reverse_lazy
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.views import View, generic

from . import forms
from accounts.tokens import account_activation_token


class MerchantRegistration(generic.CreateView):
    """
    View to register a merchant onto the platform.
    """
    form_class = forms.UserCreateForm
    success_url = reverse_lazy("login")
    template_name = "accounts/signup.html"

    def form_valid(self, form):
        """
        Set the request onto the form instance.
        :param form: UserCreateForm
        :return:
        """
        form.request = self.request
        return super().form_valid(form)


class ActivateUser(View):
    """
    Class to activate a user when they click the link sent in their emails.
    """

    def get(self, *args, **kwargs):
        """
        Validate and activate the user by turning the is_active to True.
        :param args:
        :param kwargs:
        :return:
        """
        User = get_user_model()
        try:
            uid = force_text(urlsafe_base64_decode(kwargs.get('uid')))
            user = User.objects.get(pk=uid)
        except(TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and account_activation_token.check_token(user, kwargs.get('token')):
            user.is_active = True
            user.save()
            return redirect(reverse_lazy("login"))
        return HttpResponse("Invalid activation link")  # TODO replace this with a template


class LoginSuccess(View):
    def get(self, request):
        if request.user.is_merchant:
            return redirect("merchant:dashboard")
        return redirect("shops")


class LoginOut(generic.RedirectView):
    # Url to redirect to after a user is logged out.
    url = reverse_lazy("login")

    def get(self, request, *args, **kwargs):
        """
        Log out a user
        :param request:
        :param args:
        :param kwargs:
        :return:
        """
        logout(request)
        return super().get(request, *args, **kwargs)

leadshop/accounts/views.py
from django.contrib.auth import get_user_model, logout
from django.http import HttpResponse
from django.shortcuts import redirect
from django.core.urlresolvers import reverse_lazy
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.views import View, generic

from . import forms
from leadshop.accounts.tokens import account_activation_token


class MerchantRegistration(generic.CreateView):
    """
    View to register a merchant onto the platform.
    """
    form_class = forms.UserCreateForm
    success_url = reverse_lazy("login")
    template_name = "accounts/signup.html"

    def form_valid(self, form):
        """
        Set the request onto the form instance.
        :param form: UserCreateForm
        :return:
        """
        form.request = self.request
        return super().form_valid(form)


class ActivateUser(View):
    """
    Class to activate a user when they click the link sent in their emails.
    """

    def get(self, *args, **kwargs):
        """
        Validate and activate the user by turning the is_active to True.
        :param args:
        :param kwargs:
        :return:
        """
        User = get_user_model()
        try:
            uid = force_text(urlsafe_base64_decode(kwargs.get('uid')))
            user = User.objects.get(pk=uid)
        except(TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and account_activation_token.check_token(user, kwargs.get('token')):
            user.is_active = True
            user.save()
            return redirect(reverse_lazy("login"))
        return HttpResponse("Invalid activation link")  # TODO replace this with a template


class LoginSuccess(View):
    def get(self, request):
        if request.user.is_merchant:
            return redirect("merchant:dashboard")
        return redirect("shops")


class LoginOut(generic.RedirectView):
    # Url to redirect to after a user is logged out.
    url = reverse_lazy("login")

    def get(self, request, *args, **kwargs):
        """
        Log out a user
        :param request:
        :param args:
        :param kwargs:
        :return:
        """
        logout(request)
        return super().get(request, *args, **kwargs)

leadshop/accounts/templates/accounts/account_activation_email.html
{% autoescape off %}
    Hi {{ user.username }},

    Please click on the link to confirm your registration,
    http://{{ domain }}{% url 'accounts:activate' uid=uid token=token %}
{% endautoescape %}

leadshop/accounts/templates/accounts/login.html
{% extends "layout_merchant.html" %}

{% block title %}Leadshop | Login {% endblock %}

{% block body_css %}class="hold-transition login-page"{% endblock %}

{% block body_content %}
    <div class="login-box">
        <div class="login-logo">
            <a href="#"><b>Lead</b>shop</a>
        </div>
        <!-- /.login-logo -->
        <div class="login-box-body">
            <p class="login-box-msg">Sign In</p>

            <form method="post">
                {% csrf_token %}
                <div class="form-group has-feedback">
                    <input type="email" class="form-control" placeholder="Email" name="{{ form.username.html_name }}">
                    <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                    {{ form.username.errors }}
                </div>
                <div class="form-group has-feedback">
                    <input type="password" class="form-control" placeholder="Password"
                           name={{ form.password.html_name }}>
                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                    {{ form.password.errors }}
                </div>
                <div class="row">
                    <div class="col-xs-8">
                        <div class="checkbox icheck">
                            <label>
                                <input type="checkbox"> Remember Me
                            </label>
                        </div>
                    </div>
                    <!-- /.col -->
                    <div class="col-xs-4">
                        <button type="submit" class="btn btn-primary btn-block btn-flat" value="Sign In">Sign In</button>
                    </div>
                    <!-- /.col -->
                </div>
            </form>

            <a href="{% url "password_reset" %}">I forgot my password</a><br>
            <a href="{% url "accounts:merchant_signup" %}" class="text-center">Register as a merchant</a>

        </div>
        <!-- /.login-box-body -->
    </div>
    <!-- /.login-box -->
{% endblock %}

{% block scripts %}
    <script>
        $(function () {
            $('input').iCheck({
                checkboxClass: 'icheckbox_square-blue',
                radioClass: 'iradio_square-blue',
                increaseArea: '20%' // optional
            });
        });
    </script>
{% endblock %}

leadshop/accounts/templates/accounts/signup.html
{% extends "layout_merchant.html" %}

{% block title %}Leadshop | Sign Up {% endblock %}

{% block body_css %}class="hold-transition register-page"{% endblock %}

{% block body_content %}
    <div class="register-box">
        <div class="login-logo">
            <a href="#"><b>Lead</b>shop</a>
        </div>

        <div class="register-box-body">
            <p class="login-box-msg">Register as a merchant</p>

            <form method="post">
                {% csrf_token %}
                <div class="form-group has-feedback">
                    <input type="text" class="form-control"
                           placeholder="Username"
                           name={{ form.username.html_name }}
                                   required>
                    <span class="glyphicon glyphicon-user form-control-feedback"></span>
                    {{ form.username.errors }}
                </div>
                <div class="form-group has-feedback">
                    <input type="email" class="form-control" placeholder="Email" name={{ form.email.html_name }}>
                    <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                    {{ form.email.errors }}
                </div>
                <div class="form-group has-feedback">
                    <input type="password" class="form-control" placeholder="Password"
                           name={{ form.password1.html_name }} required>
                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                    {{ form.password1.errors }}
                </div>
                <div class="form-group has-feedback">
                    <input type="password" class="form-control"
                           placeholder="Retype password" name={{ form.password2.html_name }} required>
                    <span class="glyphicon glyphicon-log-in form-control-feedback"></span>
                    {{ form.password2.errors }}
                </div>
                <div class="row">
                    <!-- /.col -->
                    <div class="col-xs-4">
                        <button type="submit" class="btn btn-primary btn-block btn-flat">Register</button>
                    </div>
                    <!-- /.col -->
                </div>
            </form>
            <a href="{% url "login" %}" class="text-center">I already have an account</a>
        </div>
        <!-- /.form-box -->
    </div>
{% endblock %}